#include <Wire.h>
#include <LiquidCrystal_I2C.h>

// สร้างอ็อบเจ็กต์ LCD: (I2C Address, Columns, Rows)
LiquidCrystal_I2C lcd(0x27, 16, 2);

#include "DHT.h"

#define DHTPIN 15        // กำหนดขาที่เชื่อมต่อกับเซ็นเซอร์ DHT11/DHT22
#define DHTTYPE DHT11   // เลือกประเภทเซ็นเซอร์ DHT11 หรือ DHT22 (ใช้ DHT11 ในที่นี้)

DHT dht(DHTPIN, DHTTYPE); // สร้างอ็อบเจ็กต์ DHT

void setup() {
  Serial.begin(115200);    // เริ่มต้นการสื่อสารผ่าน Serial Monitor
  dht.begin();             // เริ่มการทำงานของเซ็นเซอร์ DHT

  lcd.begin();              // เริ่มการทำงานของจอ LCD
  lcd.backlight();          // เปิดไฟแบ็คไลท์

  lcd.setCursor(0, 0);      // ตั้งตำแหน่งเริ่มต้น (คอลัมน์, แถว)
  lcd.print("Miss You!"); // แสดงข้อความในแถวที่ 1

  lcd.setCursor(0, 1);      // ย้ายไปแถวที่ 2
  lcd.print("By :namtarn.");

}

void loop() {
  // รอเวลาให้เซ็นเซอร์พร้อม
  delay(2000);

  // อ่านค่าอุณหภูมิและความชื้น
  float h = dht.readHumidity();        // อ่านค่าความชื้น
  float t = dht.readTemperature();     // อ่านค่าอุณหภูมิ (ในเซลเซียส)

  // ตรวจสอบค่าที่อ่านได้
  if (isnan(h) || isnan(t)) {
    Serial.println("ไม่สามารถอ่านค่าเซ็นเซอร์ได้");
    return;
  }

  // แสดงค่าที่อ่านได้
  Serial.print("อุณหภูมิ: ");
  Serial.print(t);
  Serial.print(" *C");
  Serial.print("  ความชื้น: ");
  Serial.print(h);
  Serial.println(" %");
}
